name: Kaizen Guardian - Dormancy Monitor

on:
  schedule:
    # Run daily at 00:00 UTC
    - cron: '0 0 * * *'
  
  workflow_dispatch:
    # Allow manual trigger
    inputs:
      force_check:
        description: 'Force dormancy check'
        required: false
        default: 'false'

permissions:
  contents: write  # Needed to commit elevation if triggered
  issues: write    # Needed to create notification issue

jobs:
  guardian-check:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Full history for comprehensive checking
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Run Kaizen Guardian
        env:
          OPENAI_LAB_ENDPOINT: ${{ secrets.OPENAI_LAB_ENDPOINT }}
          ANTHROPIC_LAB_ENDPOINT: ${{ secrets.ANTHROPIC_LAB_ENDPOINT }}
          DEEPSEEK_LAB_ENDPOINT: ${{ secrets.DEEPSEEK_LAB_ENDPOINT }}
          CIVIC_LEDGER_ENDPOINT: ${{ secrets.CIVIC_LEDGER_ENDPOINT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          python scripts/ceremonial_summons/kaizen_guardian.py
      
      - name: Check if README was elevated
        id: check_elevation
        run: |
          if git diff --name-only HEAD~1 HEAD | grep -q "^README.md$"; then
            echo "elevated=true" >> $GITHUB_OUTPUT
          else
            echo "elevated=false" >> $GITHUB_OUTPUT
          fi
      
      - name: Commit and push if elevation occurred
        if: steps.check_elevation.outputs.elevated == 'true'
        run: |
          git config --local user.email "guardian@kaizen-os.org"
          git config --local user.name "Kaizen Guardian"
          git push
      
      - name: Create notification issue if elevation occurred
        if: steps.check_elevation.outputs.elevated == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const issue = await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: '🔥 CEREMONIAL SUMMONS ACTIVATED - Custodian Needed',
              body: `## Ceremonial Summons Has Been Activated
            
            The Kaizen Guardian has detected that all 8 entities have been dormant for 90+ consecutive days:
            
            - ❌ Michael (@kaizencycle)
            - ❌ AUREA (OpenAI)
            - ❌ ATLAS (Anthropic)
            - ❌ SOLARA (DeepSeek)
            - ❌ JADE (Signer/Attestor)
            - ❌ EVE (Verifier/Reflector)
            - ❌ ZEUS (Overseer/Arbiter)
            - ❌ HERMES (Auditor/Messenger)
            
            **The Master README has been elevated to the repository root.**
            
            ## What This Means
            
            This is not a failure. This is the design. The founder planned for this moment.
            
            **Someone must now step forward as Custodian.**
            
            ## Next Steps for Potential Custodians
            
            1. Read the elevated README at the root of this repository
            2. Study the full documentation in \`/docs/\`
            3. Review the Custodian Guide: \`/docs/CUSTODIAN_GUIDE.md\`
            4. If you choose to accept custodianship:
               - Take the Custodian Oath
               - Create your record: \`/ledger/custodians/YOUR_NAME.json\`
               - Announce the transition to the community
               - Continue the work
            
            ## For More Information
            
            - **Elevation Log:** \`ledger/guardian/elevation_log.json\`
            - **Activity Log:** \`ledger/guardian/activity_log.json\`
            - **Custodian Guide:** \`docs/CUSTODIAN_GUIDE.md\`
            - **Manifesto:** \`docs/MANIFESTO.md\`
            
            ---
            
            *"No master. No savior. Only stewards passing the torch."*
            
            **The torch is waiting. Will you carry it?**
            `,
              labels: ['ceremonial-summons', 'custodianship', 'critical']
            });
            
            // Pin the issue
            await github.rest.issues.lock({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue.data.number,
              lock_reason: 'resolved'
            });
      
      - name: Send notification to Discord (if webhook configured)
        if: steps.check_elevation.outputs.elevated == 'true' && secrets.DISCORD_WEBHOOK_URL != ''
        run: |
          curl -X POST "${{ secrets.DISCORD_WEBHOOK_URL }}" \
            -H "Content-Type: application/json" \
            -d '{
              "embeds": [{
                "title": "🔥 CEREMONIAL SUMMONS ACTIVATED 🔥",
                "description": "All 8 entities have been dormant for 90+ days.\n\nThe Master README has been elevated.\n\n**A new Custodian is needed.**",
                "color": 16744192,
                "fields": [
                  {
                    "name": "Repository",
                    "value": "'"$GITHUB_REPOSITORY"'",
                    "inline": true
                  },
                  {
                    "name": "Timestamp",
                    "value": "'"$(date -u +%Y-%m-%dT%H:%M:%SZ)"'",
                    "inline": true
                  },
                  {
                    "name": "Next Steps",
                    "value": "Read the elevated README and consider taking the Custodian Oath"
                  }
                ],
                "footer": {
                  "text": "Kaizen Guardian | We heal as we walk"
                }
              }]
            }'
      
      - name: Upload activity logs as artifact
        uses: actions/upload-artifact@v3
        with:
          name: guardian-logs
          path: ledger/guardian/*.json
          retention-days: 365  # Keep for 1 year
